# Generated by Django 5.0 on 2023-12-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.SlugField(max_length=15, unique=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('platform', models.CharField(choices=[('IG', 'Instagram'), ('TT', 'TikTok'), ('UG', 'User Generated Content')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content_creator.creator')),
            ],
        ),
    ]
